XTMUNITW ; VEN/SMH - Coverage Test Runner;2014-04-17  3:30 PM
 ;;7.3;KERNEL TOOLKIT;;
 ;
 ; This tests code in XTMUNITV for coverage
 D EN^XTMUNIT($T(+0),1) QUIT
 ;
MAIN ; @TEST - Test coverage calculations
 D COV^XTMUNIT1("XTMUNITV","D EN^XTMUNIT(""XTMUNITV"",1)",-1)  ; Only produce output global.
 D CHKEQ^XTMUNIT(^TMP("XTMCOVREPORT",$J),"15/20")
 D CHKEQ^XTMUNIT(^TMP("XTMCOVREPORT",$J,"XTMUNITV","INTERNAL"),"3/6")
 D CHKTF^XTMUNIT($D(^TMP("XTMCOVREPORT",$J,"XTMUNITV","T2",4)))
 D CHKEQ^XTMUNIT(^TMP("XTMCOVREPORT",$J,"XTMUNITV","SETUP"),"1/1")
 QUIT
