ZZUTRED1	;JLI/FO-OAK-UNIT TESTS FOR XTMREDO CONTINUATION ;08/10/11  14:55
	;;0.0;TOOLKIT;**TEST**;
	D EN^XTMUNIT("ZZUTREDO")
	Q
	;
CONDIF2	;
	N ARRAY,EXPECTED,TESTVAL
	;D FILEINIT^XTMLOG("ZZUTXTMR")
	S ARRAY(1)=" I ARG[""$"" F I=1:1 S CH=$E(ARG,I) Q:CH=""""  D QUOTE:CH=Q I CH=""$"" D FUN"
	S ARRAY(2)=" Q"
	S EXPECTED(1)=" IF ARG[""$"" FOR I=1:1 QUIT:$$DOFOR1()"
	S EXPECTED(2)=" QUIT"
	S EXPECTED(3)=" ;"
	S EXPECTED(4)="DOFOR1() ;"
	S EXPECTED(5)=" SET CH=$EXTRACT(ARG,I)"
	S EXPECTED(6)=" QUIT:CH="""" 1"
	S EXPECTED(7)=" DO QUOTE:CH=Q"
	S EXPECTED(8)=" IF CH=""$"" DO FUN"
	S EXPECTED(9)=" QUIT 0"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	;D DEBUG^XTMLOG("EXPECTED","EXPECTED",1)
	;D DEBUG^XTMLOG("ACTUAL","ACTUAL",1)
	;D ENDLOG^XTMLOG("ZZUTXTMR")
	Q
	;
IF5	;
	N ARRAY,EXPECTED
	;D FILEINIT^XTMLOG("ZZUTXTMR")
	S ARRAY(1)=" I X>4 D E1:Y>0,E2 S K=0"
	S EXPECTED(1)=" IF X>4 DO E1:Y>0 DO E2 SET K=0"
	S ARRAY(2)=" Q",EXPECTED(2)=" QUIT"
	S ARRAY(3)="E1 S X=2",EXPECTED(3)="E1 SET X=2"
	S ARRAY(4)=" Q",EXPECTED(4)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	;D ENDLOG^XTMLOG("ZZUTXTMR")
	Q
	;
DEBUG2	; code from XTDEBUG2 with a problem
	N ARRAY,EXPECTED
	;D FILEINIT^XTMLOG("ZZUTXTMR")
	S ARRAY(1)=" S XTDEBLIN="""""
	S EXPECTED(1)=" SET XTDEBLIN="""""
	S ARRAY(2)=" S XTDEBLIN="""""
	S EXPECTED(2)=" SET XTDEBLIN="""""
	S ARRAY(3)=" I $G(XTDEBCNT)="""" S XTDEBCNT=0"
	S EXPECTED(3)=" IF $GET(XTDEBCNT)="""" SET XTDEBCNT=0"
	S ARRAY(4)=" F I=1:1 Q:$E(XTDEBINP,I)=""""  I (($E(XTDEBINP,I,I+1)=""$$"")!($E(XTDEBINP,I,I+1)=""$S"")) D"
	S EXPECTED(4)=" FOR I=1:1 QUIT:$$DOFOR1()"
	S ARRAY(5)=" . S XTDEBSRT=I"
	S ARRAY(6)=" . I $E(XTDEBINP,I,I+1)=""$S"" D  I 1"
	S ARRAY(7)=" . . S XTDEBQUO=0"
	S ARRAY(8)=" . . F I=I+1:1 Q:$E(XTDEBINP,I)=""""  Q:$E(XTDEBINP,I)=""("""
	S ARRAY(9)=" . . Q"
	S ARRAY(10)=" . E  S I=I+1,LEN=0 F  S I=I+1,LEN=LEN+1 S XTDEBCHR=$E(XTDEBINP,I) Q:XTDEBCHR=""""  S:XTDEBCHR=""^"" LEN=0 I '((XTDEBCHR?1""%"")&(LEN=1)),XTDEBCHR'?1A,XTDEBCHR'?1N,XTDEBCHR'?1""^"" Q"
	S ARRAY(11)=" Q"
	S EXPECTED(5)=" QUIT"
	S EXPECTED(6)=" ;"
	S EXPECTED(7)="DODOT1 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(8)=" SET XTDEBSRT=I"
	S EXPECTED(9)=" IF $EXTRACT(XTDEBINP,I,I+1)=""$S"" DO DODOT2 IF 1"
	S EXPECTED(10)=" IF '$TEST SET I=I+1 SET LEN=0 FOR  QUIT:$$DOFOR3()"
	S EXPECTED(11)=" DO XTGETTES QUIT"
	S EXPECTED(12)=" ;"
	S EXPECTED(13)="DODOT2 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(14)=" SET XTDEBQUO=0"
	S EXPECTED(15)=" FOR I=I+1:1 QUIT:$$DOFOR2()"
	S EXPECTED(16)=" DO XTGETTES QUIT"
	S EXPECTED(17)=" ;"
	S EXPECTED(18)="DOFOR1() ;"
	S EXPECTED(19)=" QUIT:$EXTRACT(XTDEBINP,I)="""" 1"
	S EXPECTED(20)=" IF (($EXTRACT(XTDEBINP,I,I+1)=""$$"")!($EXTRACT(XTDEBINP,I,I+1)=""$S"")) DO DODOT1"
	S EXPECTED(21)=" QUIT 0"
	S EXPECTED(22)=" ;"
	S EXPECTED(23)="DOFOR2() ;"
	S EXPECTED(24)=" QUIT:$EXTRACT(XTDEBINP,I)="""" 1"
	S EXPECTED(25)=" QUIT:$EXTRACT(XTDEBINP,I)=""("" 1"
	S EXPECTED(26)=" QUIT 0"
	S EXPECTED(27)=" ;"
	S EXPECTED(28)="DOFOR3() ;"
	S EXPECTED(29)=" SET I=I+1"
	S EXPECTED(30)=" SET LEN=LEN+1"
	S EXPECTED(31)=" SET XTDEBCHR=$EXTRACT(XTDEBINP,I)"
	S EXPECTED(32)=" QUIT:XTDEBCHR="""" 1"
	S EXPECTED(33)=" SET:XTDEBCHR=""^"" LEN=0"
	S EXPECTED(34)=" IF '((XTDEBCHR?1""%"")&(LEN=1)) IF XTDEBCHR'?1A IF XTDEBCHR'?1N IF XTDEBCHR'?1""^"" QUIT 1"
	S EXPECTED(35)=" QUIT 0"
	S EXPECTED(36)=" ;"
	S EXPECTED(37)="XTSETTES ;"
	S EXPECTED(38)=" SET XTDLRTES=$TEST"
	S EXPECTED(39)=" QUIT"
	S EXPECTED(40)=" ;"
	S EXPECTED(41)="XTGETTES ;"
	S EXPECTED(42)=" IF XTDLRTES"
	S EXPECTED(43)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	;D DEBUG^XTMLOG("EXPECTED","EXPECTED",1)
	;D DEBUG^XTMLOG("ACTUAL","ACTUAL",1)
	;D ENDLOG^XTMLOG("ZZUTXTMR")
	Q
	;
IANDCOND	;
	N ARRAY,EXPECTED
	;D FILEINIT^XTMLOG("ZZUTXTMR")
	S ARRAY(1)=" I XTDEBQUO=0 S:XTDEBCHR=""("" XTDEBPAR=XTDEBPAR+1 S:XTDEBCHR="")"" XTDEBPAR=XTDEBPAR-1"
	S EXPECTED(1)=" IF XTDEBQUO=0 SET:XTDEBCHR=""("" XTDEBPAR=XTDEBPAR+1 SET:XTDEBCHR="")"" XTDEBPAR=XTDEBPAR-1"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	;D ENDLOG^XTMLOG("ZZUTXTMR")
	Q
	;
SETPRCNT	;
	N ARRAY,EXPECTED
	;D FILEINIT^XTMLOG("ZZUTXTMR")
	S ARRAY(1)=" F I=2:1 Q:'$D(XTDEBRES(""ARGS"",I))  D"
	S ARRAY(2)=" . S:I=2 XTDEBLI1=XTDEBRES(""CMND"")_$S($D(XTDEBRES(""PRECOND"")):"":""_XTDEBRES(""PRECOND""),1:"""")_"" """
	S ARRAY(3)=" . S:I>2 XTDEBLI1=XTDEBLI1_"","" S XTDEBLI1=XTDEBLI1_XTDEBRES(""ARGS"",I)_$S($D(XTDEBRES(""ARGS"",I,""POSTCOND"")):"":""_XTDEBRES(""ARGS"",I,""POSTCOND""),1:"""")"
	S ARRAY(4)=" Q"
	S EXPECTED(1)=" FOR I=2:1 QUIT:$$DOFOR1()"
	S EXPECTED(2)=" QUIT"
	S EXPECTED(3)=" ;"
	S EXPECTED(4)="DODOT1 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(5)=" SET:I=2 XTDEBLI1=XTDEBRES(""CMND"")_$SELECT($DATA(XTDEBRES(""PRECOND"")):"":""_XTDEBRES(""PRECOND""),1:"""")_"" """
	S EXPECTED(6)=" SET:I>2 XTDEBLI1=XTDEBLI1_"","""
	S EXPECTED(7)=" SET XTDEBLI1=XTDEBLI1_XTDEBRES(""ARGS"",I)_$SELECT($DATA(XTDEBRES(""ARGS"",I,""POSTCOND"")):"":""_XTDEBRES(""ARGS"",I,""POSTCOND""),1:"""")"
	S EXPECTED(8)=" DO XTGETTES QUIT"
	S EXPECTED(9)=" ;"
	S EXPECTED(10)="DOFOR1() ;"
	S EXPECTED(11)=" QUIT:'$DATA(XTDEBRES(""ARGS"",I)) 1"
	S EXPECTED(12)=" DO DODOT1"
	S EXPECTED(13)=" QUIT 0"
	S EXPECTED(14)=" ;"
	S EXPECTED(15)="XTSETTES ;"
	S EXPECTED(16)=" SET XTDLRTES=$TEST"
	S EXPECTED(17)=" QUIT"
	S EXPECTED(18)=" ;"
	S EXPECTED(19)="XTGETTES ;"
	S EXPECTED(20)=" IF XTDLRTES"
	S EXPECTED(21)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	;D DEBUG^XTMLOG("ACTUAL","ACTUAL",1)
	;D ENDLOG^XTMLOG("ZZUTXTMR")
	Q
	;
CONDDON1	; check conditional DO with NO ARG, NO LEADING IF
	N ARRAY,EXPECTED
	S ARRAY(1)=" S X=4 D:X>0  S Y=3"
	S ARRAY(2)=" . S X=3"
	S ARRAY(3)=" . Q"
	S ARRAY(4)=" Q"
	S EXPECTED(1)=" SET X=4"
	S EXPECTED(2)=" DO:X>0 DODOT1"
	S EXPECTED(3)=" SET Y=3"
	S EXPECTED(4)=" QUIT"
	S EXPECTED(5)=" ;"
	S EXPECTED(6)="DODOT1 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(7)=" SET X=3"
	S EXPECTED(8)=" DO XTGETTES QUIT"
	S EXPECTED(9)=" ;"
	S EXPECTED(10)="XTSETTES ;"
	S EXPECTED(11)=" SET XTDLRTES=$TEST"
	S EXPECTED(12)=" QUIT"
	S EXPECTED(13)=" ;"
	S EXPECTED(14)="XTGETTES ;"
	S EXPECTED(15)=" IF XTDLRTES"
	S EXPECTED(16)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
	;
CONDDON2	; check conditional DO with NO ARG, BUT LEADING IF
	N ARRAY,EXPECTED
	S ARRAY(1)=" I X=4 D:Y>0  S Y=3"
	S ARRAY(2)=" . S X=3"
	S ARRAY(3)=" . Q"
	S ARRAY(4)=" Q"
	S EXPECTED(1)=" IF X=4 DO:Y>0 DODOT1 SET Y=3"
	S EXPECTED(2)=" QUIT"
	S EXPECTED(3)=" ;"
	S EXPECTED(4)="DODOT1 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(5)=" SET X=3"
	S EXPECTED(6)=" DO XTGETTES QUIT"
	S EXPECTED(7)=" ;"
	S EXPECTED(8)="XTSETTES ;"
	S EXPECTED(9)=" SET XTDLRTES=$TEST"
	S EXPECTED(10)=" QUIT"
	S EXPECTED(11)=" ;"
	S EXPECTED(12)="XTGETTES ;"
	S EXPECTED(13)=" IF XTDLRTES"
	S EXPECTED(14)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
	;
BROKNLIN	;one line broken when it shouldn't have
	N ARRAY,EXPECTED
	S ARRAY(1)=" I $L(DIQGXDF,"":"")>1 S DIQGXDT=$P(DIQGXDF,"":"",2) F  S DIQGXDN=$O(@DIQGXDD@(+DIQGXDN)) Q:DIQGXDN'>0!(DIQGXDN>DIQGXDT)  S DIQGXDC=$P(^(DIQGXDN,0),""^"",2)"
	S ARRAY(2)=" Q"
	S EXPECTED(1)=" IF $LENGTH(DIQGXDF,"":"")>1 SET DIQGXDT=$PIECE(DIQGXDF,"":"",2) FOR  QUIT:$$DOFOR1()"
	S EXPECTED(2)=" QUIT"
	S EXPECTED(3)=" ;"
	S EXPECTED(4)="DOFOR1() ;"
	S EXPECTED(5)=" SET DIQGXDN=$ORDER(@DIQGXDD@(+DIQGXDN))"
	S EXPECTED(6)=" QUIT:DIQGXDN'>0!(DIQGXDN>DIQGXDT) 1"
	S EXPECTED(7)=" SET DIQGXDC=$PIECE(^(DIQGXDN,0),""^"",2)"
	S EXPECTED(8)=" QUIT 0"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
	;
BADLINES	;
	N ARRAY,EXPECTED
	S ARRAY(1)=" K DIX(""K"")"
	S ARRAY(2)=" F I=0:0 S I=$O(DIKX(I)) Q:'I  F DIFLD=0:0 S DIFLD=$O(DIKX(I,DIFLD)) Q:'DIFLD  D"
	S ARRAY(3)=" . I DIFLD=.01,$G(DZ)=0 S DIY="""""
	S ARRAY(4)=" . S DIX(""K"",I,DIFLD)=$$GET1^DIQ(DIFILEI,Y_DIFILEI(DIFILEI,""KEY"",""IEN""),DIFLD,"""","""",""DIERR"") Q"
	S ARRAY(5)=" Q"
	S EXPECTED(1)=" KILL DIX(""K"")"
	S EXPECTED(2)=" FOR I=0:0 QUIT:$$DOFOR1()"
	S EXPECTED(3)=" QUIT"
	S EXPECTED(4)=" ;"
	S EXPECTED(5)="DODOT1 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(6)=" IF DIFLD=.01 IF $GET(DZ)=0 SET DIY="""""
	S EXPECTED(7)=" SET DIX(""K"",I,DIFLD)=$$GET1^DIQ(DIFILEI,Y_DIFILEI(DIFILEI,""KEY"",""IEN""),DIFLD,"""","""",""DIERR"")"
	S EXPECTED(8)=" DO XTGETTES QUIT"
	S EXPECTED(9)=" ;"
	S EXPECTED(10)="DOFOR1() ;"
	S EXPECTED(11)=" SET I=$ORDER(DIKX(I))"
	S EXPECTED(12)=" QUIT:'I 1"
	S EXPECTED(13)=" FOR DIFLD=0:0 QUIT:$$DOFOR2()"
	S EXPECTED(14)=" QUIT 0"
	S EXPECTED(15)=" ;"
	S EXPECTED(16)="DOFOR2() ;"
	S EXPECTED(17)=" SET DIFLD=$ORDER(DIKX(I,DIFLD))"
	S EXPECTED(18)=" QUIT:'DIFLD 1"
	S EXPECTED(19)=" DO DODOT1"
	S EXPECTED(20)=" QUIT 0"
	S EXPECTED(21)=" ;"
	S EXPECTED(22)="XTSETTES ;"
	S EXPECTED(23)=" SET XTDLRTES=$TEST"
	S EXPECTED(24)=" QUIT"
	S EXPECTED(25)=" ;"
	S EXPECTED(26)="XTGETTES ;"
	S EXPECTED(27)=" IF XTDLRTES"
	S EXPECTED(28)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
QUITNFOR	; QUIT IN FOR, EVEN CONDITIONAL SET 1
	N ARRAY,EXPECTED
	S ARRAY(1)=" F I=1:1 S X=4 Q:X>1"
	S ARRAY(2)=" Q"
	S EXPECTED(1)=" FOR I=1:1 QUIT:$$DOFOR1()"
	S EXPECTED(2)=" QUIT"
	S EXPECTED(3)=" ;"
	S EXPECTED(4)="DOFOR1() ;"
	S EXPECTED(5)=" SET X=4"
	S EXPECTED(6)=" QUIT:X>1 1"
	S EXPECTED(7)=" QUIT 0"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
	;
IFINFOR	; IF LINES INSIDE OF A FOR LOOP
	N ARRAY,EXPECTED
	S ARRAY(1)=" F I=1:1:DINDEX(""#"") I $G(DINDEX(I,""GETEXT""))=0 S F1=$G(DINDEX(I,""FILE"")),F2=$G(DINDEX(I,""FIELD"")) I F1=DIFILEI,F2 D"
	S ARRAY(2)=" . S F1=$F(F,(""^""_F2_""^"")) Q:'F1  S F1=F1-2"
	S ARRAY(3)=" . S $E(F,(F1-$L(F2)),F1)="""" Q"
	S ARRAY(4)=" S DINDEX(""FLISTD"")=F Q"
	S EXPECTED(1)=" FOR I=1:1:DINDEX(""#"") QUIT:$$DOFOR1()"
	S EXPECTED(2)=" SET DINDEX(""FLISTD"")=F"
	S EXPECTED(3)=" QUIT"
	S EXPECTED(4)=" ;"
	S EXPECTED(5)="DODOT1 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(6)=" SET F1=$FIND(F,(""^""_F2_""^""))"
	S EXPECTED(7)=" DO:'F1 XTGETTES QUIT:'F1"
	S EXPECTED(8)=" SET F1=F1-2"
	S EXPECTED(9)=" SET $EXTRACT(F,(F1-$LENGTH(F2)),F1)="""""
	S EXPECTED(10)=" DO XTGETTES QUIT"
	S EXPECTED(11)=" ;"
	S EXPECTED(12)="DOFOR1() ;"
	S EXPECTED(13)=" IF $GET(DINDEX(I,""GETEXT""))=0 SET F1=$GET(DINDEX(I,""FILE"")) SET F2=$GET(DINDEX(I,""FIELD"")) IF F1=DIFILEI IF F2 DO DODOT1"
	S EXPECTED(14)=" QUIT 0"
	S EXPECTED(15)=" ;"
	S EXPECTED(16)="XTSETTES ;"
	S EXPECTED(17)=" SET XTDLRTES=$TEST"
	S EXPECTED(18)=" QUIT"
	S EXPECTED(19)=" ;"
	S EXPECTED(20)="XTGETTES ;"
	S EXPECTED(21)=" IF XTDLRTES"
	S EXPECTED(22)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
	;
DBLCOND1	;
	N ARRAY,EXPECTED
	S ARRAY(1)=" S DH=$O(DU(DH)) G:DH>0 DH:$D(DV(DH)),E,F:$D(XX),G G H"
	; WAS YIELDING
	; SET DH=$ORDER(DU(DH))
	; GOTO:DH>0 DH:$DATA(DV(DH))
	; GOTO E     <===== SHOULD HAVE BEEN GOTO:DH>0 E
	S EXPECTED(1)=" SET DH=$ORDER(DU(DH))"
	S EXPECTED(2)=" GOTO:DH>0 DH:$DATA(DV(DH))"
	S EXPECTED(3)=" GOTO:DH>0 E"
	S EXPECTED(4)=" GOTO:DH>0 F:$DATA(XX)"
	S EXPECTED(5)=" GOTO:DH>0 G"
	S EXPECTED(6)=" GOTO H"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
	;
DBLCOND2	;
	N ARRAY,EXPECTED
	S ARRAY(1)=" I DJ>1!($G(DPP(0))=0) D  G Q:$D(DTOUT)!($D(DUOUT)) Q:X=""@""  G:$D(DIPP) ADD:X?1""^""1.E G D:X]"""" Q"
	; resulted in
	; IF DJ>1!($GET(DPP(0))=0) DO DODOT2 GOTO:$D(DTOUT)!($D(DUOUT)) Q QUIT:X="@"  GOTO:$D(DIPP):X?1"^"1.E ADD GOTO:X]"" D QUIT
	S EXPECTED(1)=" IF DJ>1!($GET(DPP(0))=0) DO DODOT1 GOTO Q:$DATA(DTOUT)!($DATA(DUOUT)) QUIT:X=""@""  GOTO:$DATA(DIPP) ADD:X?1""^""1.E GOTO D:X]"""" QUIT"
	S EXPECTED(2)=" ;"
	S EXPECTED(3)="DODOT1 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(4)=" DO XTGETTES QUIT"
	S EXPECTED(5)=" ;"
	S EXPECTED(6)="XTSETTES ;"
	S EXPECTED(7)=" SET XTDLRTES=$TEST"
	S EXPECTED(8)=" QUIT"
	S EXPECTED(9)=" ;"
	S EXPECTED(10)="XTGETTES ;"
	S EXPECTED(11)=" IF XTDLRTES"
	S EXPECTED(12)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
	;
FORGOTO	; CORRECT PROBLEM WITH FOR AND GOTO WITH GOTO OUT OF Q:$$DOFORn()
	N ARRAY,EXPECTED
	S ARRAY(1)=" S DIQZ=$G(^(N)) I DIQZ]"""" S A="""" F  S A=$O(^DD(DD,""GL"",N,A)) G N:A="""" D  G Q:'S"
	S ARRAY(2)=" . S W=$O(^(A,0))"
	S ARRAY(3)=" Q"
	S EXPECTED(1)=" SET DIQZ=$GET(^(N))"
	S EXPECTED(2)=" IF DIQZ]"""" SET A="""" FOR  SET A=$ORDER(^DD(DD,""GL"",N,A)) GOTO N:A="""" DO DODOT1 GOTO Q:'S"
	S EXPECTED(3)=" QUIT"
	S EXPECTED(4)=" ;"
	S EXPECTED(5)="DODOT1 NEW XTDLRTES DO XTSETTES"
	S EXPECTED(6)=" SET W=$ORDER(^(A,0))"
	S EXPECTED(7)=" DO XTGETTES QUIT"
	S EXPECTED(8)=" ;"
	S EXPECTED(9)="XTSETTES ;"
	S EXPECTED(10)=" SET XTDLRTES=$TEST"
	S EXPECTED(11)=" QUIT"
	S EXPECTED(12)=" ;"
	S EXPECTED(13)="XTGETTES ;"
	S EXPECTED(14)=" IF XTDLRTES"
	S EXPECTED(15)=" QUIT"
	D RUNTESTS^ZZUTREDO(.ARRAY,.EXPECTED)
	Q
	;
XTROU	;
	;;ZZUTREDO
XTENT	;
	;;CONDIF2;problem with if and for
	;;IF5;IF and postconditional DO
	;;DEBUG2;code from XTDEBUG2 with a problem
	;;IANDCOND;if followed by conditional commands
	;;SETPRCNT;SET percent value
	;;CONDDON1;CONDITIONAL DO WITH NO ARG NO LEADING IF
	;;CONDDON2;CONDITIONAL DO WITH NO ARG, BUT LEADING IF
	;;BROKNLIN;one line broken when it shouldn't have
	;;BADLINES;problem with this line
	;;QUITNFOR;
	;;IFINFOR;
	;;DBLCOND1;correct problem found with double conditions
	;;DBLCOND2;
	;;FORGOTO;
